build config change

diff --git a/sample/cloudbuild.yaml b/sample/cloudbuild.yaml
--- a/sample/cloudbuild.yaml
+++ b/sample/cloudbuild.yaml
@@ -1,24 +1,33 @@
 steps:
 - name: 'gcr.io/cloud-builders/docker'
   id: 'Build Image'
-  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/cicd-409404/sample/sample_ci_image:latest', '.' ]
+  args: [ 'build', '-t', 'sample_ci_image:latest', '.' ]
 
-- name: 'gcr.io/cloud-builders/docker'
+- name: 'sample_ci_image:latest'
   id: 'Run Tests'
   entrypoint: 'bash'
+  allowFailure: true
+  # It will create the file with content 'Error', then runs the tests.
+  # If tests are success, modify the content of file to 'Success'.
+  # If tests failed, this step is not marked as success or failure and the next steps will be executed.
   args: 
-    - '-c'
+    - -c
     - |
-      docker run --rm \
-      us-central1-docker.pkg.dev/cicd-409404/sample/sample_ci_image:latest \
-      python -m pytest tests/
-    
-# - name: 'us-central1-docker.pkg.dev/cicd-409404/sample/sample_ci_image:latest'
-#   id: 'Run Tests2'
-#   entrypoint: '/bin/sh'
-#   args:
-#     - '-c'
-#     - 'python -m pytest tests/'
+      echo 'Error' > /workspace/step.log && \
+      python -m pytest tests/ && \
+      echo 'Success' > /workspace/step.log
 
-images:
-- 'us-central1-docker.pkg.dev/cicd-409404/sample/sample_ci_image:latest'
+    
+- name: 'gcr.io/cloud-builders/docker'
+  id: 'Final Step'
+  entrypoint: 'bash'
+  args:
+    - -c
+    - |
+      file_content=$(cat /workspace/step.log)
+      if [[ "$file_content" == "Success" ]]; then
+        echo "Build Success"
+      else
+        echo "Build Failed"
+        exit 1
+      fi
